// api/v1/event.js
// -----------------------------------------------------------------------------
// Minimal first-party funnel-analytics sink for the ML Fitness apps.
//
// Accepts ANONYMOUS events (no PII) so the paywall / purchase funnel can be
// observed. Auth mirrors meal-scan.js: same APP_SHARED_SECRET + per-install id.
// Body: { event: string, ts?: number, context?: string }.
//
// Storage:
//   1. Always writes a structured, greppable "FUNNEL" line to the Vercel
//      Function logs (kept as the zero-infra fallback; Vercel discards it
//      within a day).
//   2. When EVENTS_SUPABASE_URL and EVENTS_SUPABASE_ANON_KEY are set, also
//      calls the log_fitness_event() RPC in the Mindful Meal Plans Supabase
//      project, which durably stores the event in public.fitness_events
//      (migration 20260918120000_fitness_events.sql in meal-plans-pivot).
//      The RPC is SECURITY DEFINER and validates event + platform itself.
//      A store failure is logged as "FUNNEL_STORE_FAIL" and never fails the
//      request: the apps fire-and-forget, so there is nothing to retry.
//
// Env vars (Vercel dashboard → Project → Settings → Environment Variables):
//   APP_SHARED_SECRET          : required; must equal the X-App-Secret header
//   EVENTS_SUPABASE_URL        : optional; Meal Plans project URL (https://<ref>.supabase.co)
//   EVENTS_SUPABASE_ANON_KEY   : optional; Meal Plans anon key (write-only via the RPC)
//
// Headers expected from the client:
//   X-App-Secret   : must equal APP_SHARED_SECRET
//   X-Install-Id   : per-install UUID generated by the app on first launch
//   X-Platform     : "ios" or "android"
//   X-App-Version  : optional; marketing version string, stored when present
// -----------------------------------------------------------------------------

const crypto = require('crypto');

function secretMatches(provided, expected) {
  if (!provided || !expected) return false;
  const a = Buffer.from(String(provided));
  const b = Buffer.from(String(expected));
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(a, b);
}

// Keep in sync with the allow-list inside log_fitness_event() (meal-plans-pivot).
const ALLOWED_EVENTS = new Set([
  'onboarding_complete',
  'first_scan',
  'paywall_shown',
  'paywall_dismissed',
  'buy_tapped',
  'purchase_success',
  'purchase_failed',
  'screen_view',
]);

const STORE_TIMEOUT_MS = 3000;

// Durable store: POST to the Meal Plans RPC. Never throws; logs on failure.
async function storeEvent(row) {
  const url = process.env.EVENTS_SUPABASE_URL;
  const key = process.env.EVENTS_SUPABASE_ANON_KEY;
  if (!url || !key) return;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), STORE_TIMEOUT_MS);
  try {
    const resp = await fetch(`${url.replace(/\/+$/, '')}/rest/v1/rpc/log_fitness_event`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        apikey: key,
        authorization: `Bearer ${key}`,
        prefer: 'return=minimal',
      },
      body: JSON.stringify({
        p_install_id: row.install,
        p_platform: row.platform,
        p_event: row.event,
        p_context: row.context ?? null,
        p_app_version: row.appVersion ?? null,
      }),
      signal: controller.signal,
    });
    if (!resp.ok) {
      let detail = '';
      try { detail = (await resp.text()).slice(0, 200); } catch { /* ignore */ }
      console.error('FUNNEL_STORE_FAIL ' + JSON.stringify({ status: resp.status, event: row.event, detail }));
    }
  } catch (err) {
    const reason = err && err.name === 'AbortError' ? 'timeout' : String(err && err.message || err);
    console.error('FUNNEL_STORE_FAIL ' + JSON.stringify({ status: 0, event: row.event, reason }));
  } finally {
    clearTimeout(timer);
  }
}

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' });

  const sharedSecret = process.env.APP_SHARED_SECRET;
  if (!sharedSecret) {
    console.error('Server misconfigured: missing APP_SHARED_SECRET');
    return res.status(500).json({ error: 'server_misconfigured' });
  }
  if (!secretMatches(req.headers['x-app-secret'], sharedSecret)) {
    return res.status(401).json({ error: 'unauthorized' });
  }

  const installId = req.headers['x-install-id'];
  if (!installId) return res.status(400).json({ error: 'missing_install_id' });
  const platform = String(req.headers['x-platform'] || '').toLowerCase();
  const appVersion = req.headers['x-app-version']
    ? String(req.headers['x-app-version']).slice(0, 32)
    : undefined;

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch { body = {}; }
  }
  body = body || {};

  const event = String(body.event || '');
  if (!ALLOWED_EVENTS.has(event)) return res.status(400).json({ error: 'invalid_event' });

  const context = body.context != null ? String(body.context).slice(0, 64) : undefined;

  const row = {
    event,
    context,
    platform,
    install: String(installId).slice(0, 36),
    appVersion,
    ts: Number(body.ts) || Math.floor(Date.now() / 1000),
  };

  // Structured, greppable. No PII: anonymous install id + event + optional context.
  console.log('FUNNEL ' + JSON.stringify({
    event: row.event,
    context: row.context,
    platform: row.platform,
    install: row.install,
    ts: row.ts,
  }));

  // Awaited on purpose: Vercel freezes the function once the response is sent.
  await storeEvent(row);

  return res.status(204).end();
};
