// Vercel serverless function — proxies meal-scan requests to Anthropic Claude.
// The ML Fitness mobile apps (iOS + Android) call this instead of hitting
// api.anthropic.com directly so the Anthropic API key never ships inside the
// app binaries. The Anthropic key lives only as a Vercel project env var.
//
// Required env vars (set in Vercel dashboard → Project → Settings → Environment Variables):
//   ANTHROPIC_API_KEY     — sk-ant-... key (used as fallback / single-key setup)
//   APP_SHARED_SECRET     — random 64-char string, also embedded in apps (release builds only)
//
// Optional env vars (set these later to split iOS + Android billing/tracking):
//   ANTHROPIC_API_KEY_IOS      — used when X-Platform: ios
//   ANTHROPIC_API_KEY_ANDROID  — used when X-Platform: android
//   Falls back to ANTHROPIC_API_KEY if the platform-specific one isn't set,
//   so you can run with one key today and split later with zero app updates.
//
// Auth headers expected from the client:
//   X-App-Secret  — must equal APP_SHARED_SECRET
//   X-Install-Id  — per-install UUID generated by the app on first launch
//   X-Platform    — "ios" or "android" (used for key routing + telemetry)
//
// Request body (JSON):
//   { "image": "<base64-encoded JPEG, no data: prefix>" }
//
// Response: passes through Anthropic's JSON response unchanged on success,
// or { error: "<code>" } on failure.
//
// Rate limits (in-memory, best-effort — Vercel cold-starts reset state):
//   10 scans / hour / install-id
//   50 scans / hour / IP
//   300 scans / hour / instance  (global cost backstop across all callers)
// These are first-pass guards; because they live in per-instance memory they
// reset on every cold start. The durable fix (Vercel KV / cross-instance store)
// is tracked in Linear. Anthropic spend-cap is the real backstop.

const crypto = require('crypto');

const RATE_WINDOW_MS = 60 * 60 * 1000;
const MAX_PER_INSTALL = 10;
const MAX_PER_IP = 50;
const MAX_PER_INSTANCE = 300; // global per-instance hourly ceiling
const MAX_IMAGE_BYTES = 3_000_000; // base64 length, ~2.25 MB original
const UPSTREAM_TIMEOUT_MS = 20_000;

const installCounts = new Map();
const ipCounts = new Map();
// Global per-instance counter. Like the Maps above, this resets on cold start;
// the durable cross-instance limit is tracked in Linear.
const instanceCount = { count: 0, firstAt: 0 };

// Sweep-on-write: drop expired entries whenever we touch a map so it can't grow
// unbounded across a warm instance's lifetime.
function sweep(map, now) {
  for (const [k, v] of map) {
    if (now - v.firstAt > RATE_WINDOW_MS) map.delete(k);
  }
}

function checkAndIncrement(map, key, max) {
  const now = Date.now();
  const entry = map.get(key);
  if (!entry || now - entry.firstAt > RATE_WINDOW_MS) {
    sweep(map, now);
    map.set(key, { count: 1, firstAt: now });
    return true;
  }
  if (entry.count >= max) return false;
  entry.count += 1;
  return true;
}

// Global backstop across every caller on this instance. Resets on cold start.
function checkInstanceLimit() {
  const now = Date.now();
  if (now - instanceCount.firstAt > RATE_WINDOW_MS) {
    instanceCount.count = 1;
    instanceCount.firstAt = now;
    return true;
  }
  if (instanceCount.count >= MAX_PER_INSTANCE) return false;
  instanceCount.count += 1;
  return true;
}

// Constant-time comparison of the client-supplied secret against the env value.
// Missing header or a length mismatch fails fast (before timingSafeEqual, which
// requires equal-length buffers).
function secretMatches(provided, expected) {
  if (typeof provided !== 'string' || provided.length === 0) return false;
  const a = Buffer.from(provided);
  const b = Buffer.from(expected);
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(a, b);
}

const PROMPT = `Analyze this food image and identify all food items. For each item provide:
1. Food name
2. Estimated quantity/portion size
3. Estimated calories
4. Estimated macros (protein, carbs, fat, and fiber in grams)
5. Confidence level (0-1)

Return ONLY valid JSON with no other text, in this exact format:
{
    "items": [
        {
            "name": "food name",
            "quantity": "portion description",
            "calories": 0,
            "protein": 0,
            "carbs": 0,
            "fat": 0,
            "fiber": 0,
            "confidence": 0.0
        }
    ],
    "totalCalories": 0,
    "confidence": 0.0
}`;

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' });

  const sharedSecret = process.env.APP_SHARED_SECRET;
  if (!sharedSecret) {
    console.error('Server misconfigured — missing APP_SHARED_SECRET');
    return res.status(500).json({ error: 'server_misconfigured' });
  }

  if (!secretMatches(req.headers['x-app-secret'], sharedSecret)) {
    return res.status(401).json({ error: 'unauthorized' });
  }

  const installId = req.headers['x-install-id'];
  if (!installId || typeof installId !== 'string' || installId.length < 8) {
    return res.status(400).json({ error: 'missing_install_id' });
  }

  // Platform routing — apps send X-Platform: ios|android. Used to pick the
  // matching Anthropic key when present, and to log per-platform usage.
  const platform = String(req.headers['x-platform'] || '').toLowerCase();
  const platformKey = platform === 'ios'
    ? process.env.ANTHROPIC_API_KEY_IOS
    : platform === 'android'
      ? process.env.ANTHROPIC_API_KEY_ANDROID
      : null;
  const apiKey = platformKey || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error('Server misconfigured — no Anthropic key for platform', platform);
    return res.status(500).json({ error: 'server_misconfigured' });
  }

  // Validate the payload BEFORE touching any rate-limit counters so malformed
  // requests can't burn per-install / per-IP / per-instance budget.
  const body = req.body;
  if (!body || typeof body.image !== 'string' || body.image.length === 0) {
    return res.status(400).json({ error: 'missing_image' });
  }
  if (body.image.length > MAX_IMAGE_BYTES) {
    return res.status(413).json({ error: 'image_too_large' });
  }

  // Global instance ceiling first (cheapest check + hard cost cap), then the
  // per-install and per-IP limits.
  if (!checkInstanceLimit()) {
    return res.status(429).json({ error: 'rate_limit_instance' });
  }

  if (!checkAndIncrement(installCounts, installId, MAX_PER_INSTALL)) {
    return res.status(429).json({ error: 'rate_limit_install', message: 'Too many scans this hour.' });
  }

  // Prefer x-real-ip (set by Vercel's edge) over the leftmost x-forwarded-for
  // hop (client-spoofable). Empty/missing IP funnels into one shared bucket so a
  // blank key can't bypass the limit.
  const ip = (req.headers['x-real-ip']
    || (req.headers['x-forwarded-for'] || '').split(',')[0]
    || '').trim() || 'no-ip';
  if (!checkAndIncrement(ipCounts, ip, MAX_PER_IP)) {
    return res.status(429).json({ error: 'rate_limit_ip' });
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS);
  try {
    const upstream = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 1024,
        messages: [{
          role: 'user',
          content: [
            { type: 'image', source: { type: 'base64', media_type: 'image/jpeg', data: body.image } },
            { type: 'text', text: PROMPT },
          ],
        }],
      }),
      signal: controller.signal,
    });

    const data = await upstream.json();
    if (!upstream.ok) {
      console.error('Anthropic error', platform || 'unknown-platform', upstream.status, JSON.stringify(data));
      return res.status(502).json({ error: 'upstream_error', status: upstream.status });
    }
    // Per-platform success logging — shows up in Vercel logs filterable by
    // platform string. Useful for usage trend monitoring without a separate
    // analytics pipeline.
    console.log('scan_ok', platform || 'unknown-platform', installId.slice(0, 8));
    return res.status(200).json(data);
  } catch (err) {
    if (err && err.name === 'AbortError') {
      console.error('Anthropic upstream timeout', platform || 'unknown-platform');
      return res.status(504).json({ error: 'upstream_timeout' });
    }
    console.error('Proxy fetch failed', err);
    return res.status(502).json({ error: 'network_error' });
  } finally {
    clearTimeout(timeout);
  }
};

// Give the upstream call headroom over the 20s AbortController timeout. Matches
// the file's CommonJS export style (equivalent of `export const config`).
module.exports.config = { maxDuration: 30 };
