// Vercel serverless function — proxies meal-scan requests to Anthropic Claude.
// The ML Fitness mobile apps (iOS + Android) call this instead of hitting
// api.anthropic.com directly so the Anthropic API key never ships inside the
// app binaries. The Anthropic key lives only as a Vercel project env var.
//
// Required env vars (set in Vercel dashboard → Project → Settings → Environment Variables):
//   ANTHROPIC_API_KEY     — sk-ant-... key
//   APP_SHARED_SECRET     — random 64-char string, also embedded in apps (release builds only)
//
// Auth headers expected from the client:
//   X-App-Secret  — must equal APP_SHARED_SECRET
//   X-Install-Id  — per-install UUID generated by the app on first launch
//
// Request body (JSON):
//   { "image": "<base64-encoded JPEG, no data: prefix>" }
//
// Response: passes through Anthropic's JSON response unchanged on success,
// or { error: "<code>" } on failure.
//
// Rate limits (in-memory, best-effort — Vercel cold-starts reset state):
//   10 scans / hour / install-id
//   50 scans / hour / IP
// These are first-pass guards; an abuse spike would warrant moving to Vercel KV
// for cross-instance persistence. Anthropic spend-cap is the real backstop.

const RATE_WINDOW_MS = 60 * 60 * 1000;
const MAX_PER_INSTALL = 10;
const MAX_PER_IP = 50;
const MAX_IMAGE_BYTES = 3_000_000; // base64 length, ~2.25 MB original

const installCounts = new Map();
const ipCounts = new Map();

function checkAndIncrement(map, key, max) {
  if (!key) return true;
  const now = Date.now();
  const entry = map.get(key);
  if (!entry || now - entry.firstAt > RATE_WINDOW_MS) {
    map.set(key, { count: 1, firstAt: now });
    return true;
  }
  if (entry.count >= max) return false;
  entry.count += 1;
  return true;
}

const PROMPT = `Analyze this food image and identify all food items. For each item provide:
1. Food name
2. Estimated quantity/portion size
3. Estimated calories
4. Estimated macros (protein, carbs, fat in grams)
5. Confidence level (0-1)

Return ONLY valid JSON with no other text, in this exact format:
{
    "items": [
        {
            "name": "food name",
            "quantity": "portion description",
            "calories": 0,
            "protein": 0,
            "carbs": 0,
            "fat": 0,
            "fiber": 0,
            "confidence": 0.0
        }
    ],
    "totalCalories": 0,
    "confidence": 0.0
}`;

module.exports = async function handler(req, res) {
  // CORS — apps don't need this since they're native HTTP clients, but useful
  // for curl/browser testing of the proxy itself.
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-App-Secret, X-Install-Id');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');

  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' });

  const sharedSecret = process.env.APP_SHARED_SECRET;
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!sharedSecret || !apiKey) {
    console.error('Server misconfigured — missing env vars');
    return res.status(500).json({ error: 'server_misconfigured' });
  }

  if (req.headers['x-app-secret'] !== sharedSecret) {
    return res.status(401).json({ error: 'unauthorized' });
  }

  const installId = req.headers['x-install-id'];
  if (!installId || typeof installId !== 'string' || installId.length < 8) {
    return res.status(400).json({ error: 'missing_install_id' });
  }

  if (!checkAndIncrement(installCounts, installId, MAX_PER_INSTALL)) {
    return res.status(429).json({ error: 'rate_limit_install', message: 'Too many scans this hour.' });
  }

  const ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim();
  if (!checkAndIncrement(ipCounts, ip, MAX_PER_IP)) {
    return res.status(429).json({ error: 'rate_limit_ip' });
  }

  const body = req.body;
  if (!body || typeof body.image !== 'string' || body.image.length === 0) {
    return res.status(400).json({ error: 'missing_image' });
  }
  if (body.image.length > MAX_IMAGE_BYTES) {
    return res.status(413).json({ error: 'image_too_large' });
  }

  try {
    const upstream = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 1024,
        messages: [{
          role: 'user',
          content: [
            { type: 'image', source: { type: 'base64', media_type: 'image/jpeg', data: body.image } },
            { type: 'text', text: PROMPT },
          ],
        }],
      }),
    });

    const data = await upstream.json();
    if (!upstream.ok) {
      console.error('Anthropic error', upstream.status, JSON.stringify(data));
      return res.status(502).json({ error: 'upstream_error', status: upstream.status });
    }
    return res.status(200).json(data);
  } catch (err) {
    console.error('Proxy fetch failed', err);
    return res.status(502).json({ error: 'network_error' });
  }
};
